remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: memz100.github.io
description: where i am doing wierd stuff with Java code
